app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(user_id):
        return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    """
    class that defines the users
    """
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index = True)
    avatar = db.Column(db.String())
    password_hashed = db.Column(db.String(255))

    pitches = db.relationship('Pitch', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hashed= generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hashed, password)

    def __repr__(self):
        return f'User {self.username}'


class Pitch(db.Model):
    """
    class that defines the pitches
    """

    __tablename__='pitches'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    pitch_actual = db.Column(db.String)
    category = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    comments = db.relationship('Comment', backref='pitch', lazy='dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, id):
        pitches = Pitch.query.filter_by(category=id).all()
        return pitches


class Comment(db.Model):
    """
    class that defines the comments on pitches
    """

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, id):
        comments = Pitch.query.filter_by(pitch_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField,SubmitField,SelectField
from wtforms.validators import Required


class PitchForm(FlaskForm):
    title = StringField('Pitch title',validators=[Required()])
    pitch = TextAreaField('Pitch body')
    category = SelectField(choices=[('coding', 'coding'),('technology','technology'),('deals','deals')])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField('Say something about this', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


db = SQLAlchemy()
bootstrap = Bootstrap()

photos = UploadSet('photos', IMAGES)
mail = Mail()

def create_app(config_name):
    """
    creating the app instance while taking in the config
    :param config_name:
    :return:
    """

    app = Flask(__name__)



    # creating from config

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # initialising the app extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Registering authentication blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import Pitch, User, Comment
from flask_login import login_required, current_user
from .forms import PitchForm, CommentForm
from .. import db, photos


@main.route('/')
def index():
    """
    Display the landing page
    :return:
    """

    title = 'Home - Pitch'

    return render_template('index.html', title=title)


@main.route('/user/<uname>')
def profile(uname):
    """
    display user profiles
    :param uname:
    :return:
    """
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    pitches = Pitch.query.filter_by(user_id=user.id).all()
    return render_template("profile/profile.html", user = user, pitches=pitches)


@main.route('/user/<uname>/update/pic', methods = ['POST'])
@login_required
def update_pic(uname):
    user= User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename= photos.save(request.files['photo'])
        path=f'profile_pics/{filename}'
        user.avatar = path
        db.session.commit()

    return redirect(url_for('main.profile', uname=uname))


@main.route('/new_pitch', methods=['GET', 'POST'])
@login_required
def new_pitch():
    """
    route to new pitch form
    :return:
    """
    form = PitchForm()

    if form.validate_on_submit():
        title = form.title.data
        pitch = form.pitch.data
        category = form.category.data

        fresh_pitch = Pitch(title=title, pitch_actual=pitch, category=category, user_id=current_user.id)

        fresh_pitch.save_pitch()

        return redirect(url_for('.profile', uname=current_user.username))
    title = 'New pitch'
    return render_template('new_pitch.html' , title=title, pitch_form=form)


@main.route('/single_pitch/<pitch_id>', methods=['GET', 'POST'])
def single_pitch(pitch_id):
    """
    route to a single post
    :return:
    """
    form = CommentForm()
    pitch = Pitch.query.filter_by(id=pitch_id).first()

    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(comment=comment, pitch_id=pitch_id)

        new_comment.save_comment()

        return redirect(url_for('.single_pitch', pitch_id=pitch.id))
    comments = Comment.query.filter_by(pitch_id=pitch_id).all()

    return render_template('lonely_pitch.html', pitch_id=pitch.id, pitch=pitch, comment_form=form, comments=comments)


@main.route('/category/<categoree>')
def category(categoree):
    """
    route to deals category
    :return:
    """
    category = Pitch.query.filter_by(category=categoree).all()
    title = categoree

    return render_template('category.html', category=category, title=title)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/category.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% for cat in category %}
        <h3><a href="{{url_for('main.single_pitch', pitch_id=cat.id)}}">{{cat.title}}:</a></h3>
    <hr>
        &emsp; &emsp; {{cat.pitch_actual}}
    <hr>
    {% endfor %}
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1><a href="{{url_for('main.category', categoree='coding')}}">Coding</a></h1>
    <h1><a href="{{url_for('main.category', categoree='technology')}}">Technology</a></h1>
    <h1><a href="{{url_for('main.category', categoree='deals')}}">Deals</a></h1>
</div>
{% endblock %}

app/templates/lonely_pitch.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <h1>{{pitch.title}}</h1>

    <p>{{pitch.pitch_actual}}</p>

    <h6>{{pitch.category}}</h6>

    {{ wtf.quick_form(comment_form) }}

    {% for comment in comments %}
        {{ comment.comment }}
    <hr>
    {% endfor %}
</div>
{% endblock %}

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> Pitch </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                  {%endif%}
                </ul>
            </div>

        </div>
    </div>
  </body>
</html>

app/templates/new_pitch.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
        <div class="container">

            {{ wtf.quick_form(pitch_form) }}
        </div>

{% endblock %}

app/templates/profile/lonely_review.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>
    {% if user.avatar %}
    <img src="{{url_for('static',filename=user.avatar)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      <a href="{{url_for('main.new_pitch')}}">New Pitch</a>
      {% endif %}

  </div>



  <!--Display pitches by profile-->
  <div class="col-md-4">


      <ul>
            {% for pitch in pitches %}
          <li>
              <div class="card">
                  <div class="card-title">
                      <strong>{{pitch.title}}</strong>
                  </div>
                  <div class="card-body">
                      {{pitch.pitch_actual}}
                  </div>
              </div>
          </li>
            {% endfor %}
      </ul>
  </div>
</div>
</div>




{% endblock %}